/*
 * Copyright 2024 HuaJ1a
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Description: 窗口属性
 *
 * Author: HuaJ1a
 * Date: 2024/6/25
 */

/**
 * 窗口大小
 */
export class WindowSize {
  public width: number = 0;

  public height: number = 0;
}

/**
 * 窗口位置
 */
export class WindowLocation {
  public x: number = 0;

  public y: number = 0;
}